#ifndef	_MY_GUID_DEFINE_H_
#define _MY_GUID_DEFINE_H_

enum	THGUID_OBJ_TYPE
{
	TGO_TYPE_ACCOUNT = 0,
	TGO_TYPE_PC = 1,
	TGO_TYPE_NPC = 2,
	TGO_TYPE_NPC_EQUIP = 3,
	TGO_TYPE_ITEM = 4,
	TGO_TYPE_ACCOUNT_ITEM = 5,
	TGO_TYPE_CHARACTER_ITEM = 6,
	TGO_TYPE_ZONE = 7,
	TGO_TYPE_CHANNEL = 8,
	TGO_TYPE_SUB_ZONE = 9,
	TGO_TYPE_MAX
};

//#define		GUID_FACTORY_SELF	1

#endif
